- name: copy the mongodb file 
  ansible.builtin.copy:
     src: mongodb.repo
     dest: /etc/yum.repos.d/mongodb.repo

- name: Installing mongodb
  ansible.builtin.package:
    name: mongodb-org 
    state: present 

- name: Updating  Listening Config 
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting mogodb
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes  

- name: Disble auto shutdwon 
  shell: disable-auto-shutdown && set-hostname {{ COMPONENT }}

- name: Loading Catalogue and Users Scahme 
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/catalogue.js"
    idempotent: yes

- name: Loading Catalogue and Users Scahme 
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/users.js"
    idempotent: yes