- name: copying the mongodb repo 
  ansible.builtin.copy:
     src: mongodb.repo 
     dest: /etc/yum.repos.d/mongodb.repo 

- name: Installing MongoDB 
  ansible.builtin.package:
    name: mongodb-org  
    state: present 

- name: Updating MongoDB Listening Config 
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting MongoDB 
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes  

- name: Download and extracting the {{ COMPONENT }} repo 
  ansible.builtin.unarchive:
    src: "{{REPO_URL}}"
    dest: /tmp 
    remote_src: yes  ## This will be yes, if the source file is not in the ANSIBLE SERVER


- name: Loading Catalogue Scahme 
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/catalogue.js"
    idempotent: yes

- name: Disabling auto shutdown 
  shell: disable-auto-shutdown && set-hostname {{ COMPONENT }}