- name: copying the mongodb repo 
  ansible.builtin.copy:
     src: mongodb.repo 
     dest: /etc/yum.repos.d/mongodb.repo 

- name: Installing nginx
  ansible.builtin.package:
    name: nginx 
    state: present 