- name: copy the mongodb file 
  ansible.builtin.copy:
     src: mongodb.repo
     dest: /etc/yum.repos.d/mongodb.repo

- name: Installing mongodb
  ansible.builtin.package:
    name: mongodb-org 
    state: present 

- name: Updating  Listening Config 
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting mogodb
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes  
- name: Download and extracting {{COMPONENT}}
  ansible.builtin.include_role:
    name: common 
    tasks_from: download 


- name: Loading Catalogue and Users Scahme 
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop: 
    - catalogue 
    - users


- name: Set-hostname 
  ansible.builtin.include_role:
    name: common 
    tasks_from: set-hostname


