- name: Demo on variables 
  hosts: all  
  vars:
    URL: play.google.com    # Global Variables
  tasks:  
    - name: Print URL
      ansible.builtin.debug:
        msg: The value of URL is {{ URL }}




