- name: Demo on variables 
  hosts: all  
  vars:
    URL: play.google.com    # Global/ Play level Variables
  tasks:  
    - name: Print URL
      ansible.builtin.debug:
        msg: The value of URL is {{ URL }}
    
    - name: printing the URL 
      ansible.builtin.debug:
        msg: The value of URL is {{ URL }} 
      vars:
        URL: task.google.com 

    - name: printing the CLI_URL 
      ansible.builtin.debug:
        msg: The value of CLI_URL is {{ CLI_URL }} 

### Which variable will have higher precedence ?

### Local Variables > Global Variables


# We can also supply the variables from the command line and we refer it as run time variables.

# How can we override the variables ?