- name: Demo on variables 
  hosts: all  
  vars:
    URL: play.google.com
  tasks:  
    - name: Print Hello from Play1 
      ansible.builtin.debug:
        msg: Hello from task1 of play1 


a=100 

