- name: Play1 
  hosts: all  
  vars:
   URL: play.google.com
  tasks:  
    - name: Print Hello from Play1 
      vars:
       URL: task.google.com
      ansible.builtin.debug:
        msg: Hello from task1 {{URL}}
    
    - name: Print Hello from Play2
      ansible.builtin.debug:
        msg: Hello from task2 {{URL}}
