
- name: Demo on facts 
  hosts: all  
  tasks:  
    - name: Priniting a fact
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }}"

    - name: Priniting a ip address
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }}"