- name: Demo on variables 
  hosts: all  
  tasks:
    - name: Run Shell Command 
      shell: uptime 
      register



### Register helps you in taking the output and can be used any where of our choice.