- name: Check whether tomcat is running or not 
  hosts: all  
  tasks:
    - name: Check tomcat is running or not 
      shell: uptime
      register: OUT 
    
    - name: Printing the Output of uptime 
      debug: 
        msg: The value of exit code is {{ OUT.rc }} and std out is {{ OUT.stdout }}