- name: Demo on conditions 
  hosts: all  
  tasks:
    - name: Run this task only for CentOS Machines 
      shell: ps -ef |grep java | grep -v grep
      register: OUT 
      ignore_errors: yes 
    
    - name: Starting tomcat 
      debug: 
        msg: Starting Tomcat 

# If any of the task fails, the subsequest task won't be executed and it will be terminated then and there it self