- name: Demo on copying the file to the remote machines 
  hosts: all 
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /srv/myfiles/foo.conf
        dest: /etc/foo.conf