- name: Install nginx
  ansible.builtin.package:
    name: nginx 
    state: present 

- name: Download and extract 
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/frontend/archive/main.zip
    dest: /tmp 
    remote_src: yes  ## This will be yes, if the source file is not in the ANSIBLE SERVER

- name: Cleanup of Old HTML Content 
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent    # Absent deletes the files.