- name: Install nginx
  ansible.builtin.package:
    name: nginx 
    state: present 

- name: Download and extract 
  ansible.builtin.unarchive:
    src: https://example.com/example.zip
    dest: /usr/local/bin
    remote_src: yes