- name: Install nginx
  ansible.builtin.package:
    name: nginx 
    state: present 

- name: Unarchive a file that  on the remote machine by link 
  ansible.builtin.unarchive:
    src: "https://github.com/stans-robot-project/frontend/archive/main.zip"
    dest: /tmp
    remote_src: yes

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /usr/share/nginx/htmlt
    state: absent


- name: Copy the file process 
  ansible.builtin.copy:
      src:  /tmp/forntend-main/static 
      dest: /usr/share/nginx/html


    