- name: Configuring the Yum Repos 
  ansible.builtin.shell: yum install {{ERLANG_URL}} -y && curl -s {{RABBITMQ_URL}} | sudo bash 

- name: Installing {{COMPONENT}} 
  ansible.builtin.package:
    name: rabbitmq-server  
    state: present 

- name: Starting {{COMPONENT}} 
  ansible.builtin.service:
    name: rabbitmq-server 
    state: started
    enabled: yes  
    daemon_reload: yes

- name: Adding 
  community.rabbitmq.rabbitmq_user:
    user: joe
    password: changeme
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present