- name: Configuring the Yum Repos 
  ansible.builtin.shell: yum install {{ERLANG_URL}} -y && curl -s {{RABBITMQ_URL}} | sudo bash 

- name: Installing {{COMPONENT}} 
  ansible.builtin.package:
    name: rabbitmq-server  
    state: present 

- name: Starting {{COMPONENT}} 
  ansible.builtin.service:
    name: 
    state: restarted
    enabled: yes  
    daemon_reload: yes