- name: Confiring Yum repo 
  ansible.builtin.shell:  curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Installing {{COMPONENT}}
  ansible.builtin.package:
    name: 
      - nodejs
      - gcc-c++ 
    state: present 

- name: Adding the User 
  ansible.builtin.include_role:
    name: "{{ APPUSER }}"
    tasks_from: create-user

- name: Download and extracting {{COMPONENT}}
  ansible.builtin.include_role:
    name: common 
    tasks_from: download 

