- name: Configure Yum Repos 
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Installing {{COMPONENT}}
  ansible.builtin.package:
    name: 
      - nodejs 
      - gcc-c++ 
    state: present   

- name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
  ansible.builtin.user:
    name: johnd