- name: Configuring NodeJS 
  ansible.builtin.include_role:
    name: common 
    tasks_from: nodejs

- name: copying the {{COMPONENT}}systemd file 
  ansible.builtin.copy:
     src: systemd.service  
     dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Starting {{COMPONENT}} 
  ansible.builtin.service:
    name: 
    state: started
    enabled: yes  

- name: Set-hostname 
  ansible.builtin.include_role:
    name: common 
    tasks_from: set-hostname