- name: Configure Yum Repos 
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Installing {{COMPONENT}}
  ansible.builtin.package:
    name: 
      - nodejs 
      - gcc-c++ 
    state: present   

- name: Creating Appuser account {{APPUSER}}
  ansible.builtin.user:
    name: "{{APPUSER}}"