- name: Installing Maven 
  ansible.builtin.package:
    name: maven 
    state: present 

- name: App user {{APPUSER}} User Creation
  ansible.builtin.include_role:
    name: common
    tasks_from: create-user

- name: Download and extracting {{COMPONENT}}
  ansible.builtin.include_role:
    name: common 
    tasks_from: download 

- name: Cleanup of {{COMPONENT}} and sorting the permissions
  ansible.builtin.include_role:
    name: common
    tasks_from: cleanup

- name: Generating the articact 
  ansible.builtin.shell: mvn clean package && mv target/shipping-1.0.jar shipping.jar
  chdir: /home/