- name: Installing {{COMPONENT}}
  ansible.builtin.package:
    name: 
      - python36
      - gcc-c++  
      - python3-devel
    state: present 

- name: App user {{APPUSER}} User Creation
  ansible.builtin.include_role:
    name: common
    tasks_from: create-user

- name: Download and extracting {{COMPONENT}}
  ansible.builtin.include_role:
    name: common 
    tasks_from: download 

- name: Cleanup of {{COMPONENT}} and sorting the permissions
  ansible.builtin.include_role:
    name: common
    tasks_from: cleanup

- name: Install Python Dependencies 
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}/


# - name: Configuring and Starting {{COMPONENT}}
#   ansible.builtin.include_role:
#     name: common 
#     tasks_from: systemd 

# - name: Set-hostname 
#   ansible.builtin.include_role:
#     name: common 
#     tasks_from: set-hostname